name: ChanceCraven
favicon: null
layout_spectrum: 0.24276
typography_spectrum: 1
title: Chance Craven
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8f8f8f'
    - '#404040'
    - '#84101d'
  brandStrength: 1
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
